### ISSUE TITLE
Can you confirm what combination of Inverter/Battery you have ?

### ISSUE THREAD

**Issue by craigcurtin-dev** [tidalvirus/alphaess-server#1]
I have followed you here from Whirlpool, and am interested in knowing which inverter it was that you got ? Do you know if it is on e of the GoodWe units (doubtful as they would talk to their servers rather than Alpha's) or is it the custom Alpha inverter that they will not disclose the specs of ?

Its interesting that Shine are using the ALpha Servers (although i heard a rumour the other day that they are in fact wholely owned by Alpha and in fact share premises etc in Australia.)

Craig

**Comment by tidalvirus** [comment]
So sorry, I totally missed this until now.
I have an Alpha SMILE-BAT-13.3P

I have two solar inverters, and I also have AC out from the battery too.

I’m actually not very knowledgeable about how these systems truly work, let me know if you have more questions though.

**Comment by tidalvirus** [comment]
To add, the inverters are NOT what I’m getting the data off, I’m getting it directly from the battery, which has a (totally insecure) wifi module.
